FROM python:3.9.1

RUN apt-get install wget
RUN pip install pandas sqlalchemy psycopg2 pyarrow polars

WORKDIR /app
COPY ingest_data_polars.py ingest_data_polars.py 

ENTRYPOINT [ "python", "ingest_data_polars.py" ]