name: pre-commit
on: push
jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.x
              uses: actions/setup-python@v2
              with:
                python-version: "3.11"
            - name: Install dependencies
              run: |
                pip install pre-commit pipenv
                pipenv install
            - name: pre-commit
              run: |
                pre-commit run